### ISSUE TITLE
difference between 'influencer' and 'dominant'

### ISSUE THREAD

**Issue by yanwu-ge** [Tsinghua-MARS-Lab/M2I#11]
In **src/dataset_waymo.py**, **line 290**, there is some comments as follows:
' # [id1, id2, label, relation_type].'
' # id1 always influencer, id2 always reactor'
' # interaction_label: 1 - bigger id agent dominant, 0 - smaller id agent dominant, 2 - no relation'
' # agent_pair_label: 1 - v2v, 2 - v2p, 3 - v2c, 4 - others'

I am confused about 'influencer' and 'dominant'. In my understanding, 'influencer' dominates the interaction. So why are there there cases in 'interaction_label' ?
Besides, when will the code used for generating the ground truth label released ?
Looking forward to your reply.

**Comment by larksq** [comment]
The interaction label which is a value in [0, 1, 2] is a redundancy designed for the ground truth label for the classification training. Examples are as follows:
[100, 0, 1, 1] 
or
[0, 100, 0, 1]

As for the codes used for generating the ground truth labels, sadly we don't have a plan to release them yet. These codes are frequently updated in our later projects and will not be compatible with earlier ones. A basic generator we used in this paper is nothing more than a series of bounding boxes overlap checking.  Shoot me an email if you need more than a toy-level label generator.
