### ISSUE TITLE
can't find your prediction results or your pre-trained models from Google Drive

### ISSUE THREAD

**Issue by Molly-my** [Tsinghua-MARS-Lab/M2I#14]
I only saw a share called 'infPred.NoTail.timeOffset.loopx2.IA.v2x.NonStop20.noIntention.0424.model.60.bin' on Google Drive, could you please help me find where is the content mentioned in README.md such as m2i.relation.v2v.VAL, validation_interactive_gt_relations.pickle and m2i.relation.v2v.zip?

**Comment by larksq** [comment]
Please use this link, the same as the link in the readme, to visit: https://drive.google.com/drive/folders/1SH8HWu8DQtwUgSFoIJOL8vJEvgFptBCD?usp=sharing

**Comment by Molly-my** [comment]
Thanks for your reply, I have sent the application on Google Drive, thank you again for your support.
