### ISSUE TITLE
Haven't got permissions yet

### ISSUE THREAD

**Issue by Molly-my** [Tsinghua-MARS-Lab/M2I#15]
Hello, last week you replied to me:
> Please use this link, the same as the link in the readme, to visit: https://drive.google.com/drive/folders/1SH8HWu8DQtwUgSFoIJOL8vJEvgFptBCD?usp=sharing

I've been applying on GoogleDrive for a week but still don't get permission, hoping to hear from you, thank you.

**Comment by larksq** [comment]
Sorry for the waiting. We have updated the access rule of that folder. You should now be able to visit and download the files.
