### ISSUE TITLE
Marginal trajectory prediction error.

### ISSUE THREAD

**Issue by BJHYZJ** [Tsinghua-MARS-Lab/M2I#16]
When I want to evaluation at step2 which named marginal trajectory predictoin , I meet a error about tensor. The script I ran can be seen at the top of the image.
![image](https://user-images.githubusercontent.com/74347732/205563284-af031ab3-9410-4c0d-b1a1-ced440623586.png)

**Comment by Hans-Lan** [comment]
The param size of NN in the checkpoint mismatches with the current Pytorch model, thus you cannot load params from the state dict. Please check the configuration of model in the training and evaluation stage.

**Comment by larksq** [comment]
Thank you for your feedback. I checked the pre-trained model. This model did not match the parameter setting in the readme leading to your error. I have updated the model on google drive. Could you please update the pre-trained model and try the evaluation again? Sorry for the previous mismatch.

**Comment by BJHYZJ** [comment]
That's great, thank you very much for your serious reply.

**Comment by BJHYZJ** [comment]
I meet another error at evaluation step2 and step3, because of len(prediction_trajectory.shape) != 4.
![image](https://user-images.githubusercontent.com/74347732/206356475-0c41191d-b28e-4cbc-a160-e534de487605.png)
