### ISSUE TITLE
What is the input for relation predictor?

### ISSUE THREAD

**Issue by TianzhuQin** [Tsinghua-MARS-Lab/M2I#2]
Hi, I am really looking forward to the code!

Before that, may I please ask what is the input for the relation predictor? Is it the whole graph, car's trajectory or any others?

Very Expect for your kind answer!

**Comment by larksq** [comment]
Hi TianZhu,

We use the same input as any typical trajectory predictor would use. These input data include the map, other agents' past trajectory with their infos (like shapes or types), and the traffic lights' states with their infos. More details can be found at [this great repo](https://github.com/Tsinghua-MARS-Lab/DenseTNT) of our backbone, the DenseTNT.  In fact, we use exactly the same input as DenseTNT use.

Let me know if you have any further questions.

Qiao
