### ISSUE TITLE
About interpolating missing trajectories 

### ISSUE THREAD

**Issue by daeunni** [Tsinghua-MARS-Lab/M2I#5]
@larksq
Hi, thank you for your nice work! 
btw, in WOMD there are some missing trajectories(**incomplete** trajectories). 

how did you handle this? 
did you interpolate missing points or just drop this whole trajectories? 

Best,

**Comment by larksq** [comment]
I am glad that you like our work.

Dealing with incomplete trajectories is a common issue for the trajectory prediction task. We did not interpolate any missing points. Instead, we mask out these points during training and leave them as they are during predicting. 

Best,
